### PR TITLE
Pressplay123's "extend duplicate script"

### PR DESCRIPTION
**Pull request by olilarkin**
This adds preliminary functionality to duplicate a project out of the IPlug source tree, useful if, like many do, you want to commit IPlug and Project files to SCM together

### CODE REVIEW

**Comment by sstillwell** [comment]
In our internal IPlug, practice is to use WDL/IPlug as a submodule of the plugin project.  That way IPlug can be maintained separately, yet still be tracked to the individual commit within the separate plugin project.  Is there anything sub-optimal with that?

**Comment by olilarkin** [comment]
Nope. This makes that possible/much easierf using the duplicate script

**Comment by olilarkin** [comment]
closing this PR because duplicating out of source doesn't work yet on windows

**Comment by pressplay123** [comment]
Strange, it works for me. I will have another look soon.

**Pull request closed without merging**
