### PR TITLE
Clear IGraphics::mInTextEntry when platform text entry is dismissed

### PR DESCRIPTION
**Pull request by olilarkin**
This PR fixes https://github.com/iPlug2/iPlug2/issues/841

### CODE REVIEW

**Comment by AlexHarker** [comment]
Thanks @olilarkin.

This fixes some significant parts of the issue, but in my case (in plugs where I'm hiding text display when the edit is in progress) it doesn't fix everything, because I store a bool when editing starts that I don't clear until SetValueFromUserInput() is called on my control.

There are a few options here:
- leave this as it is and I instead call GetUI->GetControlInTextEntry() to see if the control in question is in an edit (fixes my issues, but risks other iplug2 devs relying on a call to SetValueFromUserInput() that never comes.
- Always call SetValueFromUserInput() even if dismissing
- Add a new method to an IControl for when the entry is dismissed.

I'm not sure how common the pattern I've used is likely to be, but whilst we are looking at this we might as well consider the possible other scenarios.

**Comment by AlexHarker** [comment]
We could also (as a separate decision) add a GetInTextEntry() const() to the IControl class.

**Comment by olilarkin** [comment]
Since none of the example code exhibits this issue, I think you should go for option 1 for now.

**Comment by AlexHarker** [comment]
OK - would you object to IControl helpers to check if they are in a text entry (and possibly also a pop-up, although I don't need that and I'm not sure if we can track that)

**Comment by olilarkin** [comment]
Can you show me some code to reproduce the issue either in SRM repo or with a small example?

**Comment by AlexHarker** [comment]
Well, I'm not sure full code is needed but DraggableBase is where the issue is.

I have mInEdit which is set true when I start the TextEntry and false in SetValueFromUserInput(). I've already adapted to not have a local and instead I've added to a base class this:

 ```bool GetInTextEntry() const { return GetUI()->GetControlInTextEntry() == this; }```

Something like that in IControl might be handy.

**Comment by AlexHarker** [comment]
So the issue here is that I assume that if I start a text entry then I'll get a matching call to SetValueFromUserInput(), but that assumption isn't correct. I'm wondering if there are other cases where people need to know if the control is in a text entry.

**Pull request merged**
