### PR TITLE
Prevent warnings from type conversion

### PR DESCRIPTION
**Pull request by gvampgh**

### CODE REVIEW

**Comment by AlexHarker** [comment]
Thanks for this - this sort of thing also drives me mad.

Would you mind updating to use static_cast? I know that plug is very inconsistent in this regard, but for me static_cast is the correct/modern style and so if we're changing code we should ideally get that style in there too.

**Comment by gvampgh** [comment]
I will do it the next days, or you are free to edit it in the merge.

**Comment by AlexHarker** [comment]
Thanks. I'll merge once the change is made.

**Comment by gvampgh** [comment]
@AlexHarker done

**Comment by olilarkin** [comment]
thanks

**Pull request merged**
