### PR TITLE
Graphics web dblclick

### PR DESCRIPTION
**Pull request by AlexHarker**
Relates to #257 

I think this should feel/act roughly the same as desktop.

There was a secondary issue on Mac in that if you keep clicking fast you can a single mousedown followed by a string of double click messages. On windows you get alternating mouse down / double clicks. I've adapted the Mac code to behave like windows for consistency (which is also how the web code is written).

It would be easy enough to remove the Mac change, but this way all three platforms should behave the same.

### CODE REVIEW

**Comment by olilarkin** [comment]
Web dblclick seems to now work well, but with e.g. IPlugControls if I double click a knob on mac, it doesn't reset to default. Reverting 4738b2ebdeab5e241fd1242ea2a43d5bfb4f70f6 fixes it. Happy to merge this without 4738b2ebdeab5e241fd1242ea2a43d5bfb4f70f6

**Comment by AlexHarker** [comment]
Yes - I am an idiot - should have been modulo 2, not 1 (which would make all clicks single clicks) - updated.

**Comment by AlexHarker** [comment]
OK - now I've got it right I think (subtract 1 then mod by 2 to alternate)

**Comment by olilarkin** [comment]
addressed in b3c76d7bf5e752873e2952a91c1d46b9b9d324d8 and 8d66f76eec029ba7483f7da8c160c39669c3423f

**Pull request closed without merging**
