### PR TITLE
IGraphics::PathArc winding parameter

### PR DESCRIPTION
**Pull request by ppryamikov**
Arc direction is needed when it is a part of combined path.

### CODE REVIEW

**Comment by AlexHarker** [comment]
Thanks for pointing this out. Do you have a test case for this issue? There are currently some winding issues in general to do with NanoVG so I'd like to look a this all together if possible.

BTW - at the moment the CI is failing because IGraphicsCanvas hasn't been updated.

**Comment by ppryamikov** [comment]
I've tested it on this code
```
auto centerX = mRECT.MW();
auto centerY = mRECT.MH();
auto radius = mRECT.W() * 0.25f;
auto width = radius * 0.75f;
auto startAngle = -90.0f;
auto endAngle = +90.0f;

g.PathArc(centerX, centerY, radius - width * 0.5f, startAngle, endAngle);
g.PathArc(centerX, centerY, radius + width * 0.5f, endAngle, startAngle, kWindingCCW);
g.PathClose();
g.PathFill(IPattern(COLOR_WHITE));
```
which should draw a shape like this if everything is fine
image
and all kinds of other things if winding of either arc is wrong.

Though I've tested it only with NanoVG yet.

**Comment by ppryamikov** [comment]
Now tested it with Cairo and AGG. Fixed AGG which have misnamed parameter or different angles apparently.

Haven't tested with Canvas because not so much interested in it and also can't find info on how to build it. But if you're interested in pulling this I can take a look.

**Comment by ppryamikov** [comment]
Now tested it with Cairo and AGG. Fixed AGG which have misnamed parameter or different angles apparently.

Haven't tested with Canvas because not so much interested in it and also can't find info on how to build it. But if you're interested in pulling this I can test it too.

**Pull request merged**
