### PR TITLE
Reduce use of delete

### PR DESCRIPTION
**Pull request by AlexHarker**
These commits reduce to a minimum explicit deleting of objects in Plug code - thus most pointers are managed either by WDL containers / std::unique_ptr or some other relevant method.

The OSC / Faust / Websocket stuff could do with a quick test, but I haven't got full examples I can compile here.

### CODE REVIEW

**Comment by olilarkin** [comment]
this seems to be failing on windows:1
```
##[error]iplug\app\iplugapp_host.cpp(384,0): Error C2679: binary '=': no operator found which takes a right-hand operand of type 'RtAudio *' (or there is no acceptable conversion)
d:\a\1\s\iplug\app\iplugapp_host.cpp(384): error C2679: binary '=': no operator found which takes a right-hand operand of type 'RtAudio *' (or there is no acceptable conversion) [D:\a\1\s\Examples\IPlugEffect\projects\IPlugEffect-app.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\memory(2338): note: could be 'std::unique_ptr<RtAudio,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)'
          with
          [
              _Ty=RtAudio
          ] (compiling source file ..\..\..\IPlug\APP\IPlugAPP_host.cpp)
  c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\memory(2276): note: or       'std::unique_ptr<RtAudio,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(std::unique_ptr<_Ty,std::default_delete<_Ty>> &&) noexcept'
          with
          [
              _Ty=RtAudio
          ] (compiling source file ..\..\..\IPlug\APP\IPlugAPP_host.cpp)
  c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\memory(2202): note: or       'std::unique_ptr<RtAudio,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(std::nullptr_t) noexcept'
          with
          [
              _Ty=RtAudio
          ] (compiling source file ..\..\..\IPlug\APP\IPlugAPP_host.cpp)
  d:\a\1\s\iplug\app\iplugapp_host.cpp(384): note: while trying to match the argument list '(std::unique_ptr<RtAudio,std::default_delete<_Ty>>, RtAudio *)'
          with
          [
              _Ty=RtAudio
          ]
##[error]iplug\app\iplugapp_host.cpp(386,0): Error C2679: binary '=': no operator found which takes a right-hand operand of type 'RtAudio *' (or there is no acceptable conversion)
d:\a\1\s\iplug\app\iplugapp_host.cpp(386): error C2679: binary '=': no operator found which takes a right-hand operand of type 'RtAudio *' (or there is no acceptable conversion) [D:\a\1\s\Examples\IPlugEffect\projects\IPlugEffect-app.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\memory(2338): note: could be 'std::unique_ptr<RtAudio,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)'
          with
          [
              _Ty=RtAudio
          ] (compiling source file ..\..\..\IPlug\APP\IPlugAPP_host.cpp)
  c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\memory(2276): note: or       'std::unique_ptr<RtAudio,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(std::unique_ptr<_Ty,std::default_delete<_Ty>> &&) noexcept'
          with
          [
              _Ty=RtAudio
          ] (compiling source file ..\..\..\IPlug\APP\IPlugAPP_host.cpp)
  c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\memory(2202): note: or       'std::unique_ptr<RtAudio,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(std::nullptr_t) noexcept'
          with
          [
              _Ty=RtAudio
          ] (compiling source file ..\..\..\IPlug\APP\IPlugAPP_host.cpp)
  d:\a\1\s\iplug\app\iplugapp_host.cpp(386): note: while trying to match the argument list '(std::unique_ptr<RtAudio,std::default_delete<_Ty>>, RtAudio *)'
          with
          [
              _Ty=RtAudio
          ]
```

**Comment by AlexHarker** [comment]
Yep - just pushed a fix.

**Comment by olilarkin** [comment]
Do you prefer using .reset(new blah()) .reset(nullptr) ?

I think I prefer the = operator,  although reset makes it clearer it's a smart pointer

**Comment by AlexHarker** [comment]
Either way but I've used reset throughout including a previous PR so if you want = and consistency you or I will need to search through....

**Comment by olilarkin** [comment]
tested with faust and websocket, all good

**Pull request merged**
