### PR TITLE
Replace IMidiQueue with IPlugQueue

### PR DESCRIPTION
**Pull request by AlexHarker**
Designed to remove IMIDIQueue as per #33 

Could do with some midi testing. I've engineered it so that one can set a maximum number of MIDI message per second (currently 65536, but that should be agreed/reviewed). This should result in relatively small allocations, but also more-or-less consistent behaviour with different block sizes. My vote is to over-engineer the size so that the changes of running out of space are miniscule. The old system would grow indefinitely.

### CODE REVIEW

**Comment by AlexHarker** [comment]
The PR also simplifies the IPlugQueue class (removing ElementsAvailable() and Peek() the later of which was unused and the former which was not needed) and makes the code using the code smaller also.

**Comment by olilarkin** [comment]
seems in the IPlugInstrument example that when triggering notes via keys, note-off messages are not getting through, where as they were previously. Not yet tracked down why this is

**Comment by AlexHarker** [comment]
OK - will check - is the AAX or VST3? Other formats *shouldn't* be affected as far as I'm aware.

**Comment by olilarkin** [comment]
I tried this with the stand-alone app and VST3 in Reaper.  just to clarify IPlugInstrument  has some code for interpreting keystrokes and generating MIDI messages for some reason the note off messages are no longer working with these queue changes

**Comment by AlexHarker** [comment]
Cool - I'll review

**Comment by AlexHarker** [comment]
Have you had a chance to check MIDI from an external source?

**Comment by olilarkin** [comment]
the branch is archived here: https://github.com/olilarkin/iPlug2/tree/IMIDIQueue-removal

I am going to delete it on the main repo now, as i try to prune the branches

**Pull request closed without merging**
