### PR TITLE
Test for validity of componentHandler in IPlugVST3::SetLatency()

### PR DESCRIPTION
**Pull request by olilarkin**
from #731

### CODE REVIEW

**Comment by AlexHarker** [comment]
If the test fails does the caller need to know, or alternatively, should we not call IPlugProcessor::SEtLatency in either case so that when the component restarts the latency is correct? Otherwise I can't see where the new latency would get registered.

**Comment by TBProAudio** [comment]
You can always check in the plugin code (onparamchange, processblock, onidle) if (VST3) setlatency worked by calling getlatency(). If equal to "real" latency everything is fine :-)

**Comment by TBProAudio** [comment]
... and VST2/VST3/AAX APIs (AU I dont know currently) return status (OK, NOK) of setlatency. So even this could be checked ...
Because acceptance of latency changes depends on DAW, plugin format and plugin/DAW state.

**Comment by AlexHarker** [comment]
I'm trying to suggest whatever will minimise the need for the plug programmer to check through this - so a scenario that is simplest to use is best - to me having to call GetLatency() wouldn't achieve that, but we'll see what @olilarkin  says :-)

**Comment by sstillwell** [comment]
I'll mention that we have an instance where failure to test for valid pointer is causing a crash when testing VST3 using the VST3 SDK 'validator' command - the plugin has variable latency that is impacted by a parameter change.

**Pull request merged**
