### PR TITLE
Quantize screen scale - implements feature request in #741

### LINKED ISSUE #741: Allow UIs to be drawn only at strict @1x and @2x sizes, to maximize sharpness
It would be nice if IGraphics' previous behavior could be conditionally used, allowing it to choose between @1x and @2x screen sizes based on HiDPI screen scaling (below 150% use @1x, above 150% use @2x) - for bitmap based UIs this will maximize sharpness.

I propose a change (PR to come) allowing you to define IGRAPHICS_QUANTISE_SCREENSCALE to enable previous behavior.  Absence of this new value will continue to work as current master code is defined (scales UI to match screen scale)

### PR DESCRIPTION
**Pull request by sstillwell**
* [create an issue](https://github.com/iPlug2/iPlug2/issues/new/choose) first to outline the problem, to reference in this PR - Done - fixes #741 
* clearly describe the problem that the PR fixes - Done - see issue above, reference Slack DM discussion with Oli.
* each PR should address one thing. It can include multiple commits, but you should try and tidy up work done into logical units if possible. - Done
* pay attention to [iplug2 coding style](https://github.com/iPlug2/iPlug2/blob/master/Documentation/codingstyle.md)
* If it applies to an option e.g. IGRAPHICS_NANOVG or VST3 plug-ins, try to provide fixes for all options (e.g. all graphics backends or all plug-in formats) - Done

### CODE REVIEW

**Comment by olilarkin** [comment]
there are far to many #ifdef IGRAPHICS_QUANTISE_SCREENSCALE to accept this PR

I'm sure it can be done much more cleanly

**Comment by olilarkin** [comment]
Please can you try this branch and see if it achieves the same thing

https://github.com/iPlug2/iPlug2/tree/graphics/quantise-screenscale

**Comment by sstillwell** [comment]
I'll give it a shot at earliest opportunity.  Thanks!

**Comment by sstillwell** [comment]
@olilarkin that appears to work just fine - no negative impact on macOS, works as expected on Windows as well.

**Comment by olilarkin** [comment]
great, merged 7128892b43d2c77939869366651ad78ca15b0bc4

**Pull request closed without merging**
