### PR TITLE
Enable macOS OpenGL rendering via NSOpenGLLayer

### PR DESCRIPTION
**Pull request by olilarkin**
This PR allows macOS to use a layer backed OpenGL view for nanovg (and skia) 

It also tidies up the NanoVG WebGL context creation code and adds an OpenGL test control

### CODE REVIEW

**Comment by olilarkin** [comment]
hmm not scaling properly on retina

**Comment by AlexHarker** [comment]
Looks like this should cover #21 and #88. Is the issue with scaling on desktop or web (or both)?

**Comment by olilarkin** [comment]
Desktop, web is okay

**Comment by AlexHarker** [comment]
OK - does it just not scale for the screen?

**Comment by AlexHarker** [comment]
Isn't #21 now closable?

**Pull request merged**
