### PR TITLE
IPopupMenuControl- Fix positioning, drawing of triangles, and add color customization. Ref. issue #595

### PR DESCRIPTION
**Pull request by dmsplugins**
This Pull Request:
- Improves the appearance of triangles.
- Keeps menu panels in bounds regardless of whether or not mCallOut  is true. In the case of larger menu panels on small gui's, the menu panel may cover the control/ anchorArea that opened it. In the case of submenus, there is a function to further shift the parent menu(only applies to menus with submenus) if necessary.
- Added some setter functions to customize appearance and behavior.
See comments in IPopupMenuControl.h for more detail.

Usage example........ in Plugin Constructor:

#ifndef OS_IOS
    pGraphics->AttachPopupMenuControl(IText(textprops));
    //pGraphics->GetPopupMenuControl()->SetCalloutArrowColor(<#IColor color#>);;
    pGraphics->GetPopupMenuControl()->SetPanelColor(IColor(150, 0, 0, 0));
    pGraphics->GetPopupMenuControl()->SetCellBackgroundColor(IColor(80, 0, 255, 255));
    pGraphics->GetPopupMenuControl()->SetItemMouseoverColor(COLOR_LIGHT_GRAY);
    pGraphics->GetPopupMenuControl()->SetItemColor(textcolor);
    //pGraphics->GetPopupMenuControl()->SetDisabledItemColor(<#IColor color#>);
    //pGraphics->GetPopupMenuControl()->SetSeparatorColor(<#IColor color#>);
    pGraphics->GetPopupMenuControl()->SetShiftForSubmenus(-30.f);
    pGraphics->GetPopupMenuControl()->SetMenuForcedSouth(true);
    
    //pGraphics->GetPopupMenuControl()->SetExpandedBounds(<#const IRECT &bounds#>);
    pGraphics->GetPopupMenuControl()->SetCallout(true);
    //pGraphics->GetPopupMenuControl()->SetMaxBounds(<#const IRECT &bounds#>);
#endif

### CODE REVIEW

**Comment by olilarkin** [comment]
Thanks for this work. When i just do SetCallout(true) the arrow part is the wrong way around

Screenshot 2020-08-03 at 12 39 14

**Comment by dmsplugins** [comment]
Sorry about that...  I'll fix it

**Comment by dmsplugins** [comment]
The callout arrows do look better this way.

**Comment by dmsplugins** [comment]
There are still several issues in this PR that need to be corrected.

**Comment by dmsplugins** [comment]
Ok... This is about as far as I can go with this PR .... at least for a couple of weeks. Please excuse my overly verbose, not-so-great C++ skills. I'm giving it my best effort and even if I have to say so myself, am pretty happy with the results. I also have to say that this control that you made is pretty freekin awesome! I apologize for the multiple commits. So, in addition to the stuff mentioned in the first comment, the following improvements (I'll avoid using the word "fix" in any future PR's) have been made:

- CalculateMenuPanel() is now only called when the mouse is over a menu panel containing submenus and over a different panel cell than the last. This could probably be further optimized by iterating over every menu item in Expand() and calling it once for each item that is a submenu, but that would require splitting CalculateMenuPanel() into two different functions - one to create the submenus and the other to be called when it's time to open them. That would also cause every submenu to be created when it might not be necessary. The way it is now (in this PR) is pretty good with one exception. When rapidly moving from the submenu to the parent (especially when mCallOut is false) to a cell other than the highlighted one in the parent, sometimes you'll have two highlighted cells and the new submenu won't appear until you move to another cell. 

- SubMenus stay within bounds. If the center of a control that opens a menu containing submenus is <= the center of the UI, the submenu will appear to the right of the parent menu and to the left if otherwise. The parent menu will be either north or south of it's anchor area (depending on if the anchor is above or below the center of UI) and will shift in the appropriate direction by the amount specified by SetShiftForSubmenus() until it gets to a point where the drop shadow reaches the UI edge. They also stay in bounds vertically.

- Added callout arrows for submenus and slightly tweaked the size of all callout arrows to get rid of an annoying little gap.

- If a submenu is left of it's parent, the submenu triangles will be on the left side of the parent panels cell, pointing to the left and vice-versa if otherwise.

**Comment by dmsplugins** [comment]
Ok... This is about as far as I can go with this PR .... at least for a couple of weeks. Please excuse my overly verbose, not-so-great C++ skills. I'm giving it my best effort and even if I have to say so myself, am pretty happy with the results. I also have to say that this control that you made is pretty freekin awesome! I apologize for the multiple commits. So, in addition to the stuff mentioned in the first comment, the following improvements (I'll avoid using the word "fix" in any future PR's) have been made:

- CalculateMenuPanel() is now only called when the mouse is over a menu panel containing submenus and over a different panel cell than the last. This could probably be further optimized by iterating over every menu item in Expand() and calling it once for each item that is a submenu, but that would require splitting CalculateMenuPanel() into two different functions - one to create the submenus and the other to be called when it's time to open them. That would also cause every submenu to be created when it might not be necessary. The way it is now (in this PR) is pretty good with one exception. When rapidly moving from the submenu to the parent (especially when mCallOut is false) to a cell other than the highlighted one in the parent, sometimes you'll have two highlighted cells and the new submenu won't appear until you move to another cell. 

- SubMenus stay within bounds. If the center of a control that opens a menu containing submenus is <= the center of the UI, the submenu will appear to the right of the parent menu and to the left if otherwise. The parent menu will be either north or south of it's anchor area (depending on if the anchor is above or below the center of UI) and will shift in the appropriate direction by the amount specified by SetShiftForSubmenus() until it gets to a point where the drop shadow reaches the UI edge. They also stay in bounds vertically.

- Added callout arrows for submenus and slightly tweaked the size of all callout arrows to get rid of an annoying little gap.

- If a submenu is left of it's parent, the submenu triangles will be on the left side of the parent panels cell, pointing to the left and vice-versa if otherwise.

**Comment by dmsplugins** [comment]
Ok... This is about as far as I can go with this PR .... at least for a couple of weeks. Please excuse my overly verbose, not-so-great C++ skills. I'm giving it my best effort and even if I have to say so myself, am pretty happy with the results. I also have to say that this control that you made is pretty freekin awesome! I apologize for the multiple commits. So, in addition to the stuff mentioned in the first comment, the following improvements (I'll avoid using the word "fix" in any future PR's) have been made:

- CalculateMenuPanel() is now only called when the mouse is over a menu panel containing submenus and over a different panel cell than the last. This could probably be further optimized by iterating over every menu item in Expand() and calling it once for each item that is a submenu, but that would require splitting CalculateMenuPanel() into two different functions - one to create the submenus and the other to be called when it's time to open them. That would also cause every submenu to be created when it might not be necessary. The way it is now (in this PR) is pretty good with one exception. When rapidly moving from the submenu to the parent (especially when mCallOut is false) to a cell other than the highlighted one in the parent, sometimes you'll have two highlighted cells and the new submenu won't appear until you move to another cell. 

- SubMenus stay within bounds. If the center of a control that opens a menu containing submenus is <= the center of the UI, the submenu will appear to the right of the parent menu and to the left if otherwise. The parent menu will be either north or south of it's anchor area (depending on if the anchor is above or below the center of UI) and will shift in the appropriate direction by the amount specified by SetShiftForSubmenus() until it gets to a point where the drop shadow reaches the UI edge. They also stay in bounds vertically.

- Added callout arrows for submenus and slightly tweaked the size of all callout arrows to get rid of an annoying little gap.

- If a submenu is left of it's parent, the submenu triangles will be on the left side of the parent panels cell, pointing to the left and vice-versa if otherwise.

**Comment by olilarkin** [comment]
This is looking pretty good, but now i see menus three levels deep aren't working any more...

Screenshot 2020-08-07 at 16 14 14

**Comment by dmsplugins** [comment]
Menus with submenus that are multiple layers deep are working again.
I removed the function to set the callout arrows. They are now set to whatever color you set the Panels to.

**Comment by olilarkin** [comment]
Looking at merging this but it seems to have changed popup menu positioning. Can. you tell me how I can get what I previously had here with your changes?


position

**Comment by dmsplugins** [comment]
pGraphics->GetPopupMenuControl()->SetMenuForcedSouth(true);

That will force menus below the anchor area as long as there is enough space below the RECT

**Comment by olilarkin** [comment]
another thing... any idea why these menus are now going left?

image

**Pull request merged**
