### PR TITLE
Update Oversampler.h

### PR DESCRIPTION
**Pull request by BobFlip**
Separated nChannels to nInChannels and nOutChannels, enabling sidechain support

### CODE REVIEW

**Comment by hor-net** [comment]
+1 for me since I have a very similar implementation in my own branch and never found the time to create the pull request :)

**Comment by olilarkin** [comment]
This pull request has lots of white space downsamplers than necessary in the constructor. If you can fix listen tidy up a bit I’ll take a proper look

**Comment by BobFlip** [comment]
Will investigate when I get a chance

**Comment by olilarkin** [comment]
this feature has been added in https://github.com/iPlug2/iPlug2/commit/36a3a5d348686e42d064d61afc25fe95a2326636

**Comment by BobFlip** [comment]
Ah, great work, thanks!

**Pull request closed without merging**
