### PR TITLE
Add missing semicolons

### PR DESCRIPTION
**Pull request by gvampgh**

### CODE REVIEW

**Comment by AlexHarker** [comment]
The style currently is that the macros are used with semicolons. I noticed this recently when looking through the source.

@olilarkin - what do you think is best? I normally would define function-style macros with semicolons as in this PR and then not use semicolons when putting them in the source. I think having them defined here, and on the line of source code seems weird.

**Comment by gvampgh** [comment]
Ok, I understand it, and why this hasn't produce syntax errors before, seems to be a matter of taste.

**Comment by olilarkin** [comment]
which existing macros have semicolons on the end? i think it's better not to include semicolons

**Comment by asedev** [comment]
There should not be semicolons at the end of macros. Might cause issues with macros used as parameters of functions. And it looks wrong when used within code.

**Comment by gvampgh** [comment]
> 
> 
> There should not be semicolons at the end of macros. Might cause issues with macros used as parameters of functions. And it looks wrong when used within code.

Of course not all macros (e.g. the dozens of macros in the config) can have a semicolon at the end - this here is about coding macros.

**Comment by AlexHarker** [comment]
Personally I'd love these not to be macros but templates, but that is a harder job....

**Comment by gvampgh** [comment]
Yes, you are absolutely right, changing macros always causes recompilations. And e.g. for PARAMS_MUTEX it's weird, what happens, when it's defined in the config.

**Comment by olilarkin** [comment]
closing, see #374

**Pull request closed without merging**
