### PR TITLE
Update duplicate.py

### PR DESCRIPTION
**Pull request by btknu**
Update variable names in the message shown at the end of duplicate.py run.
Addresses https://github.com/iPlug2/iPlug2/issues/874 .

### CODE REVIEW

**Comment by olilarkin** [comment]
thanks!

**Comment by olilarkin** [comment]
done in https://github.com/iPlug2/iPlug2/commit/e37ef50f9ed30307c7e97700fbb61976a0e9c761, PLUG_UNIQUE_ID does get randomised

**Comment by btknu** [comment]
Why was the PR closed and the change copied to a different commit?

**Comment by olilarkin** [comment]
it was an accident to be honest, i didn't realise there was a PR and only noticed after I had pushed. sorry about that

**Comment by btknu** [comment]
No problem, thanks for the context.

**Pull request closed without merging**
