### PR TITLE
consider mStyle.roundness when drawing the slider's track

### PR DESCRIPTION
**Pull request by hor-net**
This PR fixes the issue highlighted in #465

### CODE REVIEW

**Comment by olilarkin** [comment]
I want to add something like this, but with the proposed code wider track sizes can look weird

image

really need to clip the inner track to rounded rect path, something like this with Skia, but not yet sure how to do it with other graphics backends

```
#ifdef IGRAPHICS_SKIA
#include "IGraphicsSkia.h"
#endif

void IVSliderControl::DrawTrack(IGraphics& g, const IRECT& filledArea)
{
  const auto cr = GetRoundedCornerRadius(mTrackBounds);

#ifdef IGRAPHICS_SKIA
  SkCanvas* canvas = (SkCanvas*) g.GetDrawContext();
  canvas->save();
  SkPath trackPath;
  trackPath.addRoundRect(SkiaRect(mTrackBounds), cr, cr);
  canvas->clipPath(trackPath, true);
  canvas->drawRect(SkiaRect(filledArea), SkiaPaint(GetColor(kX1), &mBlend));
  canvas->restore();
#else
  g.FillRoundRect(GetColor(kSH), mTrackBounds, cr, &mBlend);
  g.FillRoundRect(GetColor(kX1), filledArea, cr, &mBlend);
#endif
```

**Comment by hor-net** [comment]
How did you manage to get that effect? I've set the radius and the track width the same and it seems to look good... of course if you use a radius higher than the track width you get a weird looking slider...

Screenshot 2020-03-09 at 12 24 30

**Comment by olilarkin** [comment]
mStyle.roundness is a fraction 0-1, i presume you are setting it to something like 5?

**Comment by olilarkin** [comment]
are you drawing the filled area?

**Comment by hor-net** [comment]
Yes you are right i should have normalized to 0..1 but honestly i don't think this is useful at all, i think it's far easier to use the real radius when designing the interface, but even if I normalize that, 1 means: "the same radius as the track width" and i should not be able to go higher than one, so i still don't understand how the problem is created...

**Comment by olilarkin** [comment]
addressed in ee9b85cfac495eb9bde4447ab9afa9bd6fbbb322, thanks

**Pull request closed without merging**
