### PR TITLE
Fix issues with screen scale on web by checking for changes on each t…

### PR DESCRIPTION
**Pull request by AlexHarker**
…imer call.

this should fix up the remaining issues with #122.

Zoom is now taken into account in screen scale, but that is probably no bad thing.

### CODE REVIEW

**Comment by olilarkin** [comment]
This is working well on my non-retina screen, but on the retina screen with IPlugControls,  the bitmap frames are incorrect when I zoom in
Screen Shot 2019-04-13 at 13 45 06

**Comment by AlexHarker** [comment]
Can you check that I'm correct that this doesn't happen with canvas?

The issue here is to do with what happens on control resizing. With nanovg the bitmaps don't scale, but my guess is that they are stored as if they do. 

If you build on master zoom and reload the page with nanovg you'll see the same issue, so this PR is merely uncovering another issue, rather than creating it directly.

**Comment by AlexHarker** [comment]
OK - actually it was how NanoVG was dealing with drawing bitmaps that weren't at the right size. Now fixed.

**Comment by olilarkin** [comment]
seems to fix it

**Pull request merged**
